name: Deploy AWS MWAA
on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: AWS MWAA
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION }}
    
    - name: Deploy cloudformation 
      run: |
        cd aws
        aws cloudformation create-stack --stack-name mwaa-environment-public-network --template-body mwaa-public-network.yml --capabilities CAPABILITY_IAM



